workspace = {}

[package]
name = "tauri-bundler"
version = "0.4.0"
authors = ["George Burton <burtonageo@gmail.com>", "Lucas Fernandes Gonçalves Nogueira <lucas@quasar.dev>", "Daniel Thompson-Yvetot <denjell@sfosc.org>", "Tensor Programming <tensordeveloper@gmail.com>"]
license = "MIT/Apache-2.0"
keywords = ["bundle", "cargo", "tauri"]
repository = "https://github.com/tauri-apps/tauri"
description = "Wrap rust executables in OS-specific app bundles for Tauri"
edition = "2018"

[dependencies]
ar = "0.8.0"
chrono = "0.4"
clap = "^2"
dirs = "2.0.2"
error-chain = "0.12"
glob = "0.3.0"
icns = "0.3"
image = "0.23.0"
libflate = "0.1"
md5 = "0.7.0"
msi = "0.2"

serde = { version = "1.0", features = ["derive"] }
strsim = "0.10.0"
tar = "0.4"
target_build_utils = "0.3"
term = "0.6.1"
toml = "0.5.6"
uuid = { version = "0.8", features = ["v5"] }
walkdir = "2"

tauri-utils = {version = "0.4", path = "../../tauri-utils"}

[target.'cfg(target_os = "windows")'.dependencies]
attohttpc = { version = "0.11.1" }
regex = { version = "1" }

[target.'cfg(not(target_os = "linux"))'.dependencies]
handlebars = { version = "3.0" }
lazy_static = { version = "1.4" }
zip = { version = "0.5" }
sha2 = { version = "0.8" }
hex = { version = "0.4" }

[dev-dependencies]
tempfile = "3"

[[bin]]
name = "cargo-tauri-bundler"
path = "src/main.rs"

[features]
appimage = []
ios = []
dmg = []
